apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: deploy-to-genai-portal-###ENVIRONMENT###
  annotations: {}
  labels:
    app: genai-portal-###ENVIRONMENT### 
description: Target for GenAI portal ###ENVIRONMENT###
requireApproval: false
executionConfigs:
  - usages:
    - RENDER
    - DEPLOY
    serviceAccount: projects/###PROJECT_ID###/serviceAccounts/genai-portal-cloudbuild-sa@###PROJECT_ID###.iam.gserviceaccount.com
gke:
  cluster: projects/###PROJECT_ID###/locations/###LOCATION###/clusters/###_GKE_CLUSTER_NAME###